export type WebhookErrorCode =
  | 'MISSING_MERCHANT_ORDER_ID'
  | 'INVALID_ORDER_ID_FORMAT'
  | 'INVALID_PAYLOAD'
  | 'INVALID_SPECIAL_REFERENCE'
  | 'ORDER_REFERENCE_MISMATCH'
  | 'ORDER_NOT_FOUND'
  | 'USER_ORDER_MISMATCH'
  | 'AMOUNT_MISMATCH'
  | 'NO_FEE_RULE'
  | 'DUPLICATE_WEBHOOK'    // 
  | 'DUPLICATE_PAYMENT'  // 
  | 'UNALLOCATED_FUNDS'
  | 'MISSING_USER_ID';

// مشكلة في الداتا نفسها — مش هتتحل بـretry
export const NON_RETRYABLE_CODES = new Set<WebhookErrorCode>([
  'MISSING_MERCHANT_ORDER_ID',
  'INVALID_ORDER_ID_FORMAT',
  'INVALID_PAYLOAD',
  'INVALID_SPECIAL_REFERENCE',
  'ORDER_REFERENCE_MISMATCH',
  'ORDER_NOT_FOUND',
  'USER_ORDER_MISMATCH',
  'AMOUNT_MISMATCH',
  'UNALLOCATED_FUNDS',
  'MISSING_USER_ID',
  'DUPLICATE_WEBHOOK',
  'DUPLICATE_PAYMENT'
]);

// مشكلة مؤقتة — ممكن تتحل بـretry
export const RETRYABLE_CODES = new Set<WebhookErrorCode>([
  'NO_FEE_RULE',
]);